import { Onest } from 'next/font/google'
import './globals.css'

const oneset = Onest({ subsets: ['latin'] })

export const metadata = {
  title: 'Ohana - Eclane',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oneset.className}>{children}</body>
    </html>
  )
}
