import { Onest } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/session";

const oneset = Onest({ subsets: ["latin"] });

export const metadata = {
  title: "Ohana - Eclane",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={oneset.className}>{children}</body>
      </Providers>
    </html>
  );
}
